export const sampleProducts = [
  {
    slug: "hat-giong-cai-xanh",
    name: "Hạt Giống Cải Xanh Thủy Canh",
    category: "seeds",
    price: 39000,
    salePrice: 32000,
    images: ["/globe.svg"],
    description: "Hạt giống tỷ lệ nảy mầm cao, phù hợp cho hệ thống thủy canh tại nhà.",
    specs: { germination: "3-5 ngày", harvest: "25-30 ngày" },
    stock: 120,
    rating: 4.7,
    reviewCount: 48,
    tags: ["seed", "hydroponic"],
  },
  {
    slug: "dung-dich-a-b-500ml",
    name: "Dung Dịch Dinh Dưỡng A+B 500ml",
    category: "nutrients",
    price: 129000,
    salePrice: 115000,
    images: ["/file.svg"],
    description: "Bộ dinh dưỡng cân bằng cho rau lá và cây gia vị.",
    specs: { volume: "500ml x 2", usage: "2ml/lit" },
    stock: 80,
    rating: 4.8,
    reviewCount: 67,
    tags: ["nutrients", "ab"],
  },
  {
    slug: "chau-thong-minh-esp32",
    name: "Chậu Thông Minh ESP32 Smart Pot",
    category: "smart-pots",
    price: 1590000,
    images: ["/window.svg"],
    description: "Tích hợp cảm biến TDS, pH, nhiệt độ và điều khiển từ dashboard.",
    specs: { sensors: ["TDS", "pH", "DHT22"], connection: "WiFi" },
    stock: 25,
    rating: 4.9,
    reviewCount: 21,
    tags: ["iot", "smart-pot"],
  },
];

export const sampleAlerts = [
  "TDS thấp hơn ngưỡng tối thiểu, cân nhắc bổ sung dung dịch A+B",
  "pH đang ổn định trong vùng 5.8 - 6.3",
  "Mực nước bể chứa còn 42%",
  "Nhiệt độ môi trường 24.1°C, phù hợp tăng trưởng",
  "Lần chụp ảnh gần nhất: cây khỏe mạnh",
];
